# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('food_id', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=128)),
                ('expiration_date', models.DateField()),
                ('location', models.CharField(max_length=128)),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
