# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20170819_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=128)),
                ('mean_name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='meal',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.Product'),
        ),
    ]
