# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20170819_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
