# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20170819_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
